[package]
name = "precellar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
anndata = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "0d27ac475634ed7703ab1a23e01e6a3031a28541"}
anndata-hdf5 = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "0d27ac475634ed7703ab1a23e01e6a3031a28541"}
bed-utils = "0.6"
bwa-mem2 = { git = "https://github.com/regulatory-genomics/bwa-mem2-rust.git", rev = "765dd89560d7522fa72c99827f6fee2498cda38d" }
star-aligner = { git = "https://github.com/regulatory-genomics/star-aligner", rev = "e80f886635e323e97648fd38b0d5991f996b80c2" }
smallvec = "1.13"
bstr = "1.0"
itertools = "0.13"
indexmap = "2.5"
log = "0.4"
lexical = "6.1"
nalgebra-sparse = "0.10"
noodles = { version = "0.85", features = ["core", "gtf", "fastq", "bam", "sam", "async"] }
polars = "0.45"
rayon = "1.10"
serde = "1.0"
serde_json = "1.0"
seqspec = { workspace = true }
regex = "1.6"
env_logger = "0.11"
rand = "0.9.0"
indicatif = "0.17"

[dev-dependencies]
flate2 = "1.0"